import type { McuFamily } from "@/types/driver-template";

/** 转换为 include guard 宏名（大写 + 下划线 + _H） */
export function includeGuard(base: string): string {
  return `${base.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_H`;
}

/** 生成 C 注释块 */
export function headerComment(lines: string[]): string {
  const out: string[] = ["/**"];
  for (const l of lines) out.push(` * ${l}`);
  out.push(" * Generated by Embed Toolkit Driver Template Generator");
  out.push(" */");
  return out.join("\n");
}

/** 返回对应 MCU 的 HAL 主头文件 include 字符串（带引号） */
export function mcuHalHeader(mcu: McuFamily): string {
  switch (mcu) {
    case "stm32f1":
      return '"stm32f1xx_hal.h"';
    case "stm32f4":
      return '"stm32f4xx_hal.h"';
    case "stm32h7":
      return '"stm32h7xx_hal.h"';
    case "stm32g0":
      return '"stm32g0xx_hal.h"';
    case "stm32l4":
      return '"stm32l4xx_hal.h"';
    case "esp32":
      return '"esp_system.h"';
  }
}

/** SPI mode (0..3) → HAL 宏 */
export function spiModeMacros(mode: 0 | 1 | 2 | 3): {
  polarity: string;
  phase: string;
} {
  // CPOL: bit1 of mode; CPHA: bit0
  const polarity = (mode & 0b10) ? "SPI_POLARITY_HIGH" : "SPI_POLARITY_LOW";
  const phase = (mode & 0b01) ? "SPI_PHASE_2EDGE" : "SPI_PHASE_1EDGE";
  return { polarity, phase };
}

/** SPI prescaler 值 → HAL 宏 */
export function spiPrescalerMacro(p: number): string {
  const valid = [2, 4, 8, 16, 32, 64, 128, 256];
  const v = valid.includes(p) ? p : 16;
  return `SPI_BAUDRATEPRESCALER_${v}`;
}
