import type { ChipDefinition } from "@/types/gpio-planner";

/**
 * Generate C initialization code for the given chip and pin assignments.
 */
export function generateCode(
  chip: ChipDefinition,
  assignments: Record<number, string>
): string {
  if (chip.id === "stm32f103c8t6") {
    return generateSTM32Code(chip, assignments);
  }
  if (chip.id === "esp32") {
    return generateESP32Code(chip, assignments);
  }
  return "// Unsupported chip\n";
}

// --------------- STM32 HAL Code Generator ---------------

/** Extract port letter and pin number from STM32 pin name, e.g. "PA0" -> { port: "A", pin: 0 } */
function parseSTM32Pin(name: string): { port: string; pin: number } | null {
  const m = name.match(/^P([A-D])(\d+)$/);
  if (!m) return null;
  return { port: m[1], pin: parseInt(m[2], 10) };
}

/** Determine GPIO mode based on function name */
function getSTM32Mode(func: string): string {
  if (func === "GPIO_Output") return "GPIO_MODE_OUTPUT_PP";
  if (func === "GPIO_Input") return "GPIO_MODE_INPUT";
  if (func.startsWith("ADC") || func.startsWith("DAC")) return "GPIO_MODE_ANALOG";
  // Alternate function push-pull for peripherals
  return "GPIO_MODE_AF_PP";
}

/** Determine pull-up/pull-down based on function */
function getSTM32Pull(func: string): string {
  if (func === "GPIO_Input") return "GPIO_NOPULL";
  return "GPIO_NOPULL";
}

/** Determine speed */
function getSTM32Speed(func: string): string {
  if (func === "GPIO_Output") return "GPIO_SPEED_FREQ_LOW";
  return "GPIO_SPEED_FREQ_HIGH";
}

function generateSTM32Code(
  chip: ChipDefinition,
  assignments: Record<number, string>
): string {
  // Group assignments by port
  const portPins = new Map<string, { pin: number; pinName: string; func: string }[]>();

  for (const pinDef of chip.pins) {
    const func = assignments[pinDef.number];
    if (!func) continue;

    const parsed = parseSTM32Pin(pinDef.name);
    if (!parsed) continue;

    const list = portPins.get(parsed.port) ?? [];
    list.push({ pin: parsed.pin, pinName: pinDef.name, func });
    portPins.set(parsed.port, list);
  }

  if (portPins.size === 0) {
    return "// No GPIO pins assigned\n// Use the planner to assign pin functions\n";
  }

  const lines: string[] = [];
  lines.push("// GPIO Configuration - Generated by Embed Toolkit");
  lines.push("// Chip: STM32F103C8T6 (LQFP48)");
  lines.push(`// Date: ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("#include \"stm32f1xx_hal.h\"");
  lines.push("");
  lines.push("void GPIO_Init(void) {");
  lines.push("    GPIO_InitTypeDef GPIO_InitStruct = {0};");
  lines.push("");

  // Enable clocks for all used ports
  const sortedPorts = [...portPins.keys()].sort();
  for (const port of sortedPorts) {
    lines.push(`    __HAL_RCC_GPIO${port}_CLK_ENABLE();`);
  }
  lines.push("");

  // Configure each port's pins
  for (const port of sortedPorts) {
    const pins = portPins.get(port)!;
    for (const { pin, pinName, func } of pins) {
      lines.push(`    // ${pinName} - ${func}`);
      lines.push(`    GPIO_InitStruct.Pin = GPIO_PIN_${pin};`);
      lines.push(`    GPIO_InitStruct.Mode = ${getSTM32Mode(func)};`);
      lines.push(`    GPIO_InitStruct.Pull = ${getSTM32Pull(func)};`);
      lines.push(`    GPIO_InitStruct.Speed = ${getSTM32Speed(func)};`);
      lines.push(`    HAL_GPIO_Init(GPIO${port}, &GPIO_InitStruct);`);
      lines.push("");
    }
  }

  lines.push("}");
  return lines.join("\n");
}

// --------------- ESP32 Arduino Code Generator ---------------

/** Extract GPIO number from ESP32 pin name, e.g. "GPIO23" -> 23 */
function parseESP32Pin(name: string): number | null {
  const m = name.match(/GPIO(\d+)/);
  if (!m) return null;
  return parseInt(m[1], 10);
}

function getESP32PinMode(func: string): string {
  if (func === "GPIO_Output") return "OUTPUT";
  if (func === "GPIO_Input") return "INPUT";
  if (func.startsWith("ADC") || func.startsWith("DAC") || func.startsWith("TOUCH")) {
    return "INPUT"; // analog/touch uses input mode
  }
  return "OUTPUT"; // peripheral default
}

function generateESP32Code(
  chip: ChipDefinition,
  assignments: Record<number, string>
): string {
  const assignedPins: { gpioNum: number; pinName: string; func: string }[] = [];

  for (const pinDef of chip.pins) {
    const func = assignments[pinDef.number];
    if (!func) continue;

    const gpioNum = parseESP32Pin(pinDef.name);
    if (gpioNum === null) continue;

    assignedPins.push({ gpioNum, pinName: pinDef.name, func });
  }

  if (assignedPins.length === 0) {
    return "// No GPIO pins assigned\n// Use the planner to assign pin functions\n";
  }

  // Sort by GPIO number
  assignedPins.sort((a, b) => a.gpioNum - b.gpioNum);

  const lines: string[] = [];
  lines.push("// GPIO Configuration - Generated by Embed Toolkit");
  lines.push("// Chip: ESP32-WROOM-32 (38-pin DevKit)");
  lines.push(`// Date: ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("#include <Arduino.h>");
  lines.push("");

  // Define pin constants
  lines.push("// Pin definitions");
  for (const { gpioNum, func } of assignedPins) {
    const constName = `PIN_${func.replace(/[^A-Za-z0-9_]/g, "_").toUpperCase()}`;
    lines.push(`#define ${constName} ${gpioNum}`);
  }
  lines.push("");

  lines.push("void gpio_init(void) {");

  // Basic GPIO pins
  const basicPins = assignedPins.filter(
    (p) => p.func === "GPIO_Output" || p.func === "GPIO_Input"
  );
  if (basicPins.length > 0) {
    lines.push("    // Basic GPIO configuration");
    for (const { gpioNum, pinName, func } of basicPins) {
      lines.push(`    pinMode(${gpioNum}, ${getESP32PinMode(func)});  // ${pinName} - ${func}`);
    }
    lines.push("");
  }

  // Peripheral pins
  const peripheralPins = assignedPins.filter(
    (p) => p.func !== "GPIO_Output" && p.func !== "GPIO_Input"
  );

  // UART
  const uartPins = peripheralPins.filter((p) => p.func.includes("UART"));
  if (uartPins.length > 0) {
    lines.push("    // UART configuration");
    const tx = uartPins.find((p) => p.func.includes("TX"));
    const rx = uartPins.find((p) => p.func.includes("RX"));
    if (tx && rx && (tx.func.includes("UART2") || rx.func.includes("UART2"))) {
      lines.push(`    Serial2.begin(115200, SERIAL_8N1, ${rx.gpioNum}, ${tx.gpioNum});`);
    } else if (tx && rx && (tx.func.includes("UART0") || rx.func.includes("UART0"))) {
      lines.push(`    Serial.begin(115200);  // TX=${tx.gpioNum}, RX=${rx.gpioNum}`);
    }
    lines.push("");
  }

  // SPI
  const spiPins = peripheralPins.filter(
    (p) => p.func.includes("SPI") || p.func.includes("HSPI") || p.func.includes("VSPI")
  );
  if (spiPins.length > 0) {
    lines.push("    // SPI configuration");
    for (const { gpioNum, pinName, func } of spiPins) {
      lines.push(`    // ${pinName} -> ${func} (GPIO ${gpioNum})`);
    }
    lines.push("    // SPI.begin(CLK, MISO, MOSI, SS);");
    const clk = spiPins.find((p) => p.func.includes("CLK"));
    const miso = spiPins.find((p) => p.func.includes("MISO"));
    const mosi = spiPins.find((p) => p.func.includes("MOSI"));
    const ss = spiPins.find((p) => p.func.includes("SS"));
    if (clk && miso && mosi) {
      lines.push(
        `    SPI.begin(${clk.gpioNum}, ${miso.gpioNum}, ${mosi.gpioNum}${ss ? `, ${ss.gpioNum}` : ""});`
      );
    }
    lines.push("");
  }

  // I2C
  const i2cPins = peripheralPins.filter(
    (p) => p.func.includes("I2C") || p.func.includes("WIRE")
  );
  if (i2cPins.length > 0) {
    lines.push("    // I2C configuration");
    const sda = i2cPins.find((p) => p.func.includes("SDA"));
    const scl = i2cPins.find((p) => p.func.includes("SCL"));
    if (sda && scl) {
      lines.push(`    Wire.begin(${sda.gpioNum}, ${scl.gpioNum});`);
    }
    lines.push("");
  }

  // ADC
  const adcPins = peripheralPins.filter((p) => p.func.startsWith("ADC"));
  if (adcPins.length > 0) {
    lines.push("    // ADC configuration");
    for (const { gpioNum, func } of adcPins) {
      lines.push(`    analogReadResolution(12);  // ${func} on GPIO ${gpioNum}`);
      break; // only need to set resolution once
    }
    lines.push("");
  }

  // DAC
  const dacPins = peripheralPins.filter((p) => p.func.startsWith("DAC"));
  if (dacPins.length > 0) {
    lines.push("    // DAC configuration");
    for (const { gpioNum, func } of dacPins) {
      lines.push(`    // ${func} on GPIO ${gpioNum} - use dacWrite(${gpioNum}, value)`);
    }
    lines.push("");
  }

  // Touch
  const touchPins = peripheralPins.filter((p) => p.func.startsWith("TOUCH"));
  if (touchPins.length > 0) {
    lines.push("    // Touch configuration");
    for (const { gpioNum, func } of touchPins) {
      lines.push(`    // ${func} on GPIO ${gpioNum} - use touchRead(${gpioNum})`);
    }
    lines.push("");
  }

  // Remaining peripheral pins
  const handledFuncs = new Set([
    ...uartPins.map((p) => p.func),
    ...spiPins.map((p) => p.func),
    ...i2cPins.map((p) => p.func),
    ...adcPins.map((p) => p.func),
    ...dacPins.map((p) => p.func),
    ...touchPins.map((p) => p.func),
  ]);
  const remainingPins = peripheralPins.filter((p) => !handledFuncs.has(p.func));
  if (remainingPins.length > 0) {
    lines.push("    // Other peripheral pins");
    for (const { gpioNum, pinName, func } of remainingPins) {
      lines.push(`    pinMode(${gpioNum}, OUTPUT);  // ${pinName} - ${func}`);
    }
    lines.push("");
  }

  lines.push("}");
  return lines.join("\n");
}
