import type { ChipDefinition } from "@/types/gpio-planner";

/**
 * STM32F103ZET6 — LQFP144 package
 * ARM Cortex-M3 72 MHz, 512 KB Flash, 64 KB RAM
 * 5 USART, 3 SPI, 2 I2C, USB, CAN, 2 DAC, FSMC, SDIO
 * Full pin-out, AF mapping based on STM32F103 datasheet
 */
export const STM32F103ZET6: ChipDefinition = {
  id: "stm32f103zet6",
  name: "STM32F103ZET6",
  manufacturer: "STMicroelectronics",
  package: "LQFP144",
  pins: [
    // Pin 1-24
    { number: 1, name: "PE2", defaultFunction: "GPIO", alternateFunctions: ["TRACECLK", "FSMC_A23", "GPIO_Output", "GPIO_Input"] },
    { number: 2, name: "PE3", defaultFunction: "GPIO", alternateFunctions: ["TRACED0", "FSMC_A19", "GPIO_Output", "GPIO_Input"] },
    { number: 3, name: "PE4", defaultFunction: "GPIO", alternateFunctions: ["TRACED1", "FSMC_A20", "GPIO_Output", "GPIO_Input"] },
    { number: 4, name: "PE5", defaultFunction: "GPIO", alternateFunctions: ["TRACED2", "FSMC_A21", "GPIO_Output", "GPIO_Input"] },
    { number: 5, name: "PE6", defaultFunction: "GPIO", alternateFunctions: ["TRACED3", "FSMC_A22", "GPIO_Output", "GPIO_Input"] },
    { number: 6, name: "VBAT", defaultFunction: "Power", alternateFunctions: [] },
    { number: 7, name: "PC13", defaultFunction: "GPIO", alternateFunctions: ["TAMPER-RTC", "GPIO_Output", "GPIO_Input"] },
    { number: 8, name: "PC14", defaultFunction: "GPIO", alternateFunctions: ["OSC32_IN", "GPIO_Output", "GPIO_Input"] },
    { number: 9, name: "PC15", defaultFunction: "GPIO", alternateFunctions: ["OSC32_OUT", "GPIO_Output", "GPIO_Input"] },
    { number: 10, name: "PF0", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A0", "GPIO_Output", "GPIO_Input"] },
    { number: 11, name: "PF1", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A1", "GPIO_Output", "GPIO_Input"] },
    { number: 12, name: "PF2", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A2", "GPIO_Output", "GPIO_Input"] },
    { number: 13, name: "PF3", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A3", "ADC3_IN9", "GPIO_Output", "GPIO_Input"] },
    { number: 14, name: "PF4", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A4", "ADC3_IN14", "GPIO_Output", "GPIO_Input"] },
    { number: 15, name: "PF5", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A5", "ADC3_IN15", "GPIO_Output", "GPIO_Input"] },
    { number: 16, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 17, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 18, name: "PF6", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NIORD", "ADC3_IN4", "GPIO_Output", "GPIO_Input"] },
    { number: 19, name: "PF7", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NREG", "ADC3_IN5", "GPIO_Output", "GPIO_Input"] },
    { number: 20, name: "PF8", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NIOWR", "ADC3_IN6", "GPIO_Output", "GPIO_Input"] },
    { number: 21, name: "PF9", defaultFunction: "GPIO", alternateFunctions: ["FSMC_CD", "ADC3_IN7", "GPIO_Output", "GPIO_Input"] },
    { number: 22, name: "PF10", defaultFunction: "GPIO", alternateFunctions: ["FSMC_INTR", "ADC3_IN8", "GPIO_Output", "GPIO_Input"] },
    { number: 23, name: "OSC_IN", defaultFunction: "OSC_IN", alternateFunctions: [] },
    { number: 24, name: "OSC_OUT", defaultFunction: "OSC_OUT", alternateFunctions: [] },

    // Pin 25-48
    { number: 25, name: "NRST", defaultFunction: "Reset", alternateFunctions: [] },
    { number: 26, name: "PC0", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN10", "GPIO_Output", "GPIO_Input"] },
    { number: 27, name: "PC1", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN11", "GPIO_Output", "GPIO_Input"] },
    { number: 28, name: "PC2", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN12", "GPIO_Output", "GPIO_Input"] },
    { number: 29, name: "PC3", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN13", "GPIO_Output", "GPIO_Input"] },
    { number: 30, name: "VSSA", defaultFunction: "Power", alternateFunctions: [] },
    { number: 31, name: "VREF-", defaultFunction: "Power", alternateFunctions: [] },
    { number: 32, name: "VREF+", defaultFunction: "Power", alternateFunctions: [] },
    { number: 33, name: "VDDA", defaultFunction: "Power", alternateFunctions: [] },
    { number: 34, name: "PA0", defaultFunction: "GPIO", alternateFunctions: ["USART2_CTS", "ADC123_IN0", "TIM2_CH1", "TIM2_ETR", "TIM5_CH1", "TIM8_ETR", "WKUP", "GPIO_Output", "GPIO_Input"] },
    { number: 35, name: "PA1", defaultFunction: "GPIO", alternateFunctions: ["USART2_RTS", "ADC123_IN1", "TIM2_CH2", "TIM5_CH2", "GPIO_Output", "GPIO_Input"] },
    { number: 36, name: "PA2", defaultFunction: "GPIO", alternateFunctions: ["USART2_TX", "ADC123_IN2", "TIM2_CH3", "TIM5_CH3", "GPIO_Output", "GPIO_Input"] },
    { number: 37, name: "PA3", defaultFunction: "GPIO", alternateFunctions: ["USART2_RX", "ADC123_IN3", "TIM2_CH4", "TIM5_CH4", "GPIO_Output", "GPIO_Input"] },
    { number: 38, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 39, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 40, name: "PA4", defaultFunction: "GPIO", alternateFunctions: ["SPI1_NSS", "USART2_CK", "ADC12_IN4", "DAC_OUT1", "GPIO_Output", "GPIO_Input"] },
    { number: 41, name: "PA5", defaultFunction: "GPIO", alternateFunctions: ["SPI1_SCK", "ADC12_IN5", "DAC_OUT2", "GPIO_Output", "GPIO_Input"] },
    { number: 42, name: "PA6", defaultFunction: "GPIO", alternateFunctions: ["SPI1_MISO", "ADC12_IN6", "TIM3_CH1", "TIM1_BKIN", "TIM8_BKIN", "GPIO_Output", "GPIO_Input"] },
    { number: 43, name: "PA7", defaultFunction: "GPIO", alternateFunctions: ["SPI1_MOSI", "ADC12_IN7", "TIM3_CH2", "TIM1_CH1N", "TIM8_CH1N", "GPIO_Output", "GPIO_Input"] },
    { number: 44, name: "PC4", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN14", "GPIO_Output", "GPIO_Input"] },
    { number: 45, name: "PC5", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN15", "GPIO_Output", "GPIO_Input"] },
    { number: 46, name: "PB0", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN8", "TIM3_CH3", "TIM1_CH2N", "TIM8_CH2N", "GPIO_Output", "GPIO_Input"] },
    { number: 47, name: "PB1", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN9", "TIM3_CH4", "TIM1_CH3N", "TIM8_CH3N", "GPIO_Output", "GPIO_Input"] },
    { number: 48, name: "PB2", defaultFunction: "GPIO/BOOT1", alternateFunctions: ["GPIO_Output", "GPIO_Input"] },

    // Pin 49-72
    { number: 49, name: "PF11", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NIOS16", "GPIO_Output", "GPIO_Input"] },
    { number: 50, name: "PF12", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A6", "GPIO_Output", "GPIO_Input"] },
    { number: 51, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 52, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 53, name: "PF13", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A7", "GPIO_Output", "GPIO_Input"] },
    { number: 54, name: "PF14", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A8", "GPIO_Output", "GPIO_Input"] },
    { number: 55, name: "PF15", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A9", "GPIO_Output", "GPIO_Input"] },
    { number: 56, name: "PG0", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A10", "GPIO_Output", "GPIO_Input"] },
    { number: 57, name: "PG1", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A11", "GPIO_Output", "GPIO_Input"] },
    { number: 58, name: "PE7", defaultFunction: "GPIO", alternateFunctions: ["TIM1_ETR", "FSMC_D4", "GPIO_Output", "GPIO_Input"] },
    { number: 59, name: "PE8", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH1N", "FSMC_D5", "GPIO_Output", "GPIO_Input"] },
    { number: 60, name: "PE9", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH1", "FSMC_D6", "GPIO_Output", "GPIO_Input"] },
    { number: 61, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 62, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 63, name: "PE10", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH2N", "FSMC_D7", "GPIO_Output", "GPIO_Input"] },
    { number: 64, name: "PE11", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH2", "FSMC_D8", "GPIO_Output", "GPIO_Input"] },
    { number: 65, name: "PE12", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH3N", "FSMC_D9", "GPIO_Output", "GPIO_Input"] },
    { number: 66, name: "PE13", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH3", "FSMC_D10", "GPIO_Output", "GPIO_Input"] },
    { number: 67, name: "PE14", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH4", "FSMC_D11", "GPIO_Output", "GPIO_Input"] },
    { number: 68, name: "PE15", defaultFunction: "GPIO", alternateFunctions: ["TIM1_BKIN", "FSMC_D12", "GPIO_Output", "GPIO_Input"] },
    { number: 69, name: "PB10", defaultFunction: "GPIO", alternateFunctions: ["I2C2_SCL", "USART3_TX", "TIM2_CH3", "GPIO_Output", "GPIO_Input"] },
    { number: 70, name: "PB11", defaultFunction: "GPIO", alternateFunctions: ["I2C2_SDA", "USART3_RX", "TIM2_CH4", "GPIO_Output", "GPIO_Input"] },
    { number: 71, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 72, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },

    // Pin 73-96
    { number: 73, name: "PB12", defaultFunction: "GPIO", alternateFunctions: ["SPI2_NSS", "I2C2_SMBA", "USART3_CK", "TIM1_BKIN", "GPIO_Output", "GPIO_Input"] },
    { number: 74, name: "PB13", defaultFunction: "GPIO", alternateFunctions: ["SPI2_SCK", "USART3_CTS", "TIM1_CH1N", "GPIO_Output", "GPIO_Input"] },
    { number: 75, name: "PB14", defaultFunction: "GPIO", alternateFunctions: ["SPI2_MISO", "USART3_RTS", "TIM1_CH2N", "GPIO_Output", "GPIO_Input"] },
    { number: 76, name: "PB15", defaultFunction: "GPIO", alternateFunctions: ["SPI2_MOSI", "TIM1_CH3N", "GPIO_Output", "GPIO_Input"] },
    { number: 77, name: "PD8", defaultFunction: "GPIO", alternateFunctions: ["USART3_TX (remap)", "FSMC_D13", "GPIO_Output", "GPIO_Input"] },
    { number: 78, name: "PD9", defaultFunction: "GPIO", alternateFunctions: ["USART3_RX (remap)", "FSMC_D14", "GPIO_Output", "GPIO_Input"] },
    { number: 79, name: "PD10", defaultFunction: "GPIO", alternateFunctions: ["USART3_CK (remap)", "FSMC_D15", "GPIO_Output", "GPIO_Input"] },
    { number: 80, name: "PD11", defaultFunction: "GPIO", alternateFunctions: ["USART3_CTS (remap)", "FSMC_A16", "GPIO_Output", "GPIO_Input"] },
    { number: 81, name: "PD12", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH1 (remap)", "USART3_RTS (remap)", "FSMC_A17", "GPIO_Output", "GPIO_Input"] },
    { number: 82, name: "PD13", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH2 (remap)", "FSMC_A18", "GPIO_Output", "GPIO_Input"] },
    { number: 83, name: "PD14", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH3 (remap)", "FSMC_D0", "GPIO_Output", "GPIO_Input"] },
    { number: 84, name: "PD15", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH4 (remap)", "FSMC_D1", "GPIO_Output", "GPIO_Input"] },
    { number: 85, name: "PG2", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A12", "GPIO_Output", "GPIO_Input"] },
    { number: 86, name: "PG3", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A13", "GPIO_Output", "GPIO_Input"] },
    { number: 87, name: "PG4", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A14", "GPIO_Output", "GPIO_Input"] },
    { number: 88, name: "PG5", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A15", "GPIO_Output", "GPIO_Input"] },
    { number: 89, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 90, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 91, name: "PG6", defaultFunction: "GPIO", alternateFunctions: ["FSMC_INT2", "GPIO_Output", "GPIO_Input"] },
    { number: 92, name: "PG7", defaultFunction: "GPIO", alternateFunctions: ["FSMC_INT3", "GPIO_Output", "GPIO_Input"] },
    { number: 93, name: "PG8", defaultFunction: "GPIO", alternateFunctions: ["GPIO_Output", "GPIO_Input"] },
    { number: 94, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 95, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 96, name: "PC6", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH1 (remap)", "TIM8_CH1", "SDIO_D6", "GPIO_Output", "GPIO_Input"] },

    // Pin 97-120
    { number: 97, name: "PC7", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH2 (remap)", "TIM8_CH2", "SDIO_D7", "GPIO_Output", "GPIO_Input"] },
    { number: 98, name: "PC8", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH3 (remap)", "TIM8_CH3", "SDIO_D0", "GPIO_Output", "GPIO_Input"] },
    { number: 99, name: "PC9", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH4 (remap)", "TIM8_CH4", "SDIO_D1", "GPIO_Output", "GPIO_Input"] },
    { number: 100, name: "PA8", defaultFunction: "GPIO", alternateFunctions: ["USART1_CK", "TIM1_CH1", "MCO", "GPIO_Output", "GPIO_Input"] },
    { number: 101, name: "PA9", defaultFunction: "GPIO", alternateFunctions: ["USART1_TX", "TIM1_CH2", "GPIO_Output", "GPIO_Input"] },
    { number: 102, name: "PA10", defaultFunction: "GPIO", alternateFunctions: ["USART1_RX", "TIM1_CH3", "GPIO_Output", "GPIO_Input"] },
    { number: 103, name: "PA11", defaultFunction: "GPIO", alternateFunctions: ["USART1_CTS", "USB_DM", "CAN_RX", "TIM1_CH4", "GPIO_Output", "GPIO_Input"] },
    { number: 104, name: "PA12", defaultFunction: "GPIO", alternateFunctions: ["USART1_RTS", "USB_DP", "CAN_TX", "TIM1_ETR", "GPIO_Output", "GPIO_Input"] },
    { number: 105, name: "PA13", defaultFunction: "SWDIO", alternateFunctions: ["JTMS", "SWDIO", "GPIO_Output", "GPIO_Input"] },
    { number: 106, name: "NC", defaultFunction: "NC", alternateFunctions: [] },
    { number: 107, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 108, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 109, name: "PA14", defaultFunction: "SWCLK", alternateFunctions: ["JTCK", "SWCLK", "GPIO_Output", "GPIO_Input"] },
    { number: 110, name: "PA15", defaultFunction: "JTDI", alternateFunctions: ["JTDI", "TIM2_CH1", "TIM2_ETR", "SPI1_NSS (remap)", "SPI3_NSS", "GPIO_Output", "GPIO_Input"] },
    { number: 111, name: "PC10", defaultFunction: "GPIO", alternateFunctions: ["USART3_TX (partial remap)", "UART4_TX", "SPI3_SCK", "GPIO_Output", "GPIO_Input"] },
    { number: 112, name: "PC11", defaultFunction: "GPIO", alternateFunctions: ["USART3_RX (partial remap)", "UART4_RX", "SPI3_MISO", "GPIO_Output", "GPIO_Input"] },
    { number: 113, name: "PC12", defaultFunction: "GPIO", alternateFunctions: ["UART5_TX", "SPI3_MOSI", "GPIO_Output", "GPIO_Input"] },
    { number: 114, name: "PD0", defaultFunction: "GPIO", alternateFunctions: ["CAN_RX (remap)", "FSMC_D2", "GPIO_Output", "GPIO_Input"] },
    { number: 115, name: "PD1", defaultFunction: "GPIO", alternateFunctions: ["CAN_TX (remap)", "FSMC_D3", "GPIO_Output", "GPIO_Input"] },
    { number: 116, name: "PD2", defaultFunction: "GPIO", alternateFunctions: ["TIM3_ETR", "UART5_RX", "SDIO_CMD", "GPIO_Output", "GPIO_Input"] },
    { number: 117, name: "PD3", defaultFunction: "GPIO", alternateFunctions: ["USART2_CTS (remap)", "FSMC_CLK", "GPIO_Output", "GPIO_Input"] },
    { number: 118, name: "PD4", defaultFunction: "GPIO", alternateFunctions: ["USART2_RTS (remap)", "FSMC_NOE", "GPIO_Output", "GPIO_Input"] },
    { number: 119, name: "PD5", defaultFunction: "GPIO", alternateFunctions: ["USART2_TX (remap)", "FSMC_NWE", "GPIO_Output", "GPIO_Input"] },
    { number: 120, name: "PD6", defaultFunction: "GPIO", alternateFunctions: ["USART2_RX (remap)", "FSMC_NWAIT", "GPIO_Output", "GPIO_Input"] },

    // Pin 121-144
    { number: 121, name: "PD7", defaultFunction: "GPIO", alternateFunctions: ["USART2_CK (remap)", "FSMC_NE1", "GPIO_Output", "GPIO_Input"] },
    { number: 122, name: "PG9", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NE2", "FSMC_NCE3", "GPIO_Output", "GPIO_Input"] },
    { number: 123, name: "PG10", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NCE4_1", "FSMC_NE3", "GPIO_Output", "GPIO_Input"] },
    { number: 124, name: "PG11", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NCE4_2", "GPIO_Output", "GPIO_Input"] },
    { number: 125, name: "PG12", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NE4", "GPIO_Output", "GPIO_Input"] },
    { number: 126, name: "PG13", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A24", "GPIO_Output", "GPIO_Input"] },
    { number: 127, name: "PG14", defaultFunction: "GPIO", alternateFunctions: ["FSMC_A25", "GPIO_Output", "GPIO_Input"] },
    { number: 128, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 129, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 130, name: "PG15", defaultFunction: "GPIO", alternateFunctions: ["GPIO_Output", "GPIO_Input"] },
    { number: 131, name: "PB3", defaultFunction: "JTDO", alternateFunctions: ["JTDO", "TRACESWO", "TIM2_CH2", "SPI1_SCK (remap)", "SPI3_SCK", "GPIO_Output", "GPIO_Input"] },
    { number: 132, name: "PB4", defaultFunction: "JNTRST", alternateFunctions: ["JNTRST", "TIM3_CH1", "SPI1_MISO (remap)", "SPI3_MISO", "GPIO_Output", "GPIO_Input"] },
    { number: 133, name: "PB5", defaultFunction: "GPIO", alternateFunctions: ["I2C1_SMBA", "TIM3_CH2", "SPI1_MOSI (remap)", "SPI3_MOSI", "GPIO_Output", "GPIO_Input"] },
    { number: 134, name: "PB6", defaultFunction: "GPIO", alternateFunctions: ["I2C1_SCL", "TIM4_CH1", "USART1_TX (remap)", "GPIO_Output", "GPIO_Input"] },
    { number: 135, name: "PB7", defaultFunction: "GPIO", alternateFunctions: ["I2C1_SDA", "TIM4_CH2", "USART1_RX (remap)", "FSMC_NL", "GPIO_Output", "GPIO_Input"] },
    { number: 136, name: "BOOT0", defaultFunction: "Boot", alternateFunctions: [] },
    { number: 137, name: "PB8", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH3", "I2C1_SCL (remap)", "SDIO_D4", "CAN_RX (remap)", "GPIO_Output", "GPIO_Input"] },
    { number: 138, name: "PB9", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH4", "I2C1_SDA (remap)", "SDIO_D5", "CAN_TX (remap)", "GPIO_Output", "GPIO_Input"] },
    { number: 139, name: "PE0", defaultFunction: "GPIO", alternateFunctions: ["TIM4_ETR", "FSMC_NBL0", "GPIO_Output", "GPIO_Input"] },
    { number: 140, name: "PE1", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NBL1", "GPIO_Output", "GPIO_Input"] },
    { number: 141, name: "PDR_ON", defaultFunction: "Power", alternateFunctions: [] },
    { number: 142, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 143, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 144, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
  ],
};
