import type { ChipDefinition } from "@/types/gpio-planner";

/**
 * STM32F407VET6 — LQFP100 package
 * ARM Cortex-M4 168 MHz, 512 KB Flash, 192 KB RAM
 * 4 USART + 2 UART, 3 SPI, 3 I2C, USB OTG FS/HS, Ethernet, DCMI, FSMC
 * AF mapping based on STM32F407 datasheet Table 9 (Alternate function mapping)
 */
export const STM32F407VET6: ChipDefinition = {
  id: "stm32f407vet6",
  name: "STM32F407VET6",
  manufacturer: "STMicroelectronics",
  package: "LQFP100",
  pins: [
    // ---- Pin 1–25 ----
    { number: 1, name: "PE2", defaultFunction: "GPIO", alternateFunctions: ["TRACECLK", "SPI4_SCK (AF5)", "SAI1_MCLK_A (AF6)", "ETH_TXD3 (AF11)", "FSMC_A23 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 2, name: "PE3", defaultFunction: "GPIO", alternateFunctions: ["TRACED0", "SPI4_NSS (AF5)", "SAI1_SD_B (AF6)", "FSMC_A19 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 3, name: "PE4", defaultFunction: "GPIO", alternateFunctions: ["TRACED1", "SPI4_NSS (AF5)", "SAI1_FS_A (AF6)", "FSMC_A20 (AF12)", "DCMI_D4 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 4, name: "PE5", defaultFunction: "GPIO", alternateFunctions: ["TRACED2", "TIM9_CH1 (AF3)", "SPI4_MISO (AF5)", "SAI1_SCK_A (AF6)", "FSMC_A21 (AF12)", "DCMI_D6 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 5, name: "PE6", defaultFunction: "GPIO", alternateFunctions: ["TRACED3", "TIM9_CH2 (AF3)", "SPI4_MOSI (AF5)", "SAI1_SD_A (AF6)", "FSMC_A22 (AF12)", "DCMI_D7 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 6, name: "VBAT", defaultFunction: "Power", alternateFunctions: [] },
    { number: 7, name: "PC13", defaultFunction: "GPIO", alternateFunctions: ["RTC_AF1", "GPIO_Output", "GPIO_Input"] },
    { number: 8, name: "PC14", defaultFunction: "GPIO", alternateFunctions: ["OSC32_IN", "GPIO_Output", "GPIO_Input"] },
    { number: 9, name: "PC15", defaultFunction: "GPIO", alternateFunctions: ["OSC32_OUT", "GPIO_Output", "GPIO_Input"] },
    { number: 10, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 11, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 12, name: "PH0", defaultFunction: "OSC_IN", alternateFunctions: ["OSC_IN", "GPIO_Output", "GPIO_Input"] },
    { number: 13, name: "PH1", defaultFunction: "OSC_OUT", alternateFunctions: ["OSC_OUT", "GPIO_Output", "GPIO_Input"] },
    { number: 14, name: "NRST", defaultFunction: "Reset", alternateFunctions: [] },
    { number: 15, name: "PC0", defaultFunction: "GPIO", alternateFunctions: ["ADC123_IN10", "USB_OTG_HS_ULPI_STP (AF10)", "GPIO_Output", "GPIO_Input"] },
    { number: 16, name: "PC1", defaultFunction: "GPIO", alternateFunctions: ["ADC123_IN11", "ETH_MDC (AF11)", "GPIO_Output", "GPIO_Input"] },
    { number: 17, name: "PC2", defaultFunction: "GPIO", alternateFunctions: ["ADC123_IN12", "SPI2_MISO (AF5)", "USB_OTG_HS_ULPI_DIR (AF10)", "ETH_TXD2 (AF11)", "GPIO_Output", "GPIO_Input"] },
    { number: 18, name: "PC3", defaultFunction: "GPIO", alternateFunctions: ["ADC123_IN13", "SPI2_MOSI (AF5)", "USB_OTG_HS_ULPI_NXT (AF10)", "ETH_TX_CLK (AF11)", "GPIO_Output", "GPIO_Input"] },
    { number: 19, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 20, name: "VSSA", defaultFunction: "Power", alternateFunctions: [] },
    { number: 21, name: "VREF+", defaultFunction: "Power", alternateFunctions: [] },
    { number: 22, name: "VDDA", defaultFunction: "Power", alternateFunctions: [] },
    { number: 23, name: "PA0", defaultFunction: "GPIO", alternateFunctions: ["USART2_CTS (AF7)", "UART4_TX (AF8)", "ETH_CRS (AF11)", "TIM2_CH1 (AF1)", "TIM5_CH1 (AF2)", "TIM8_ETR (AF3)", "ADC123_IN0", "WKUP", "GPIO_Output", "GPIO_Input"] },
    { number: 24, name: "PA1", defaultFunction: "GPIO", alternateFunctions: ["USART2_RTS (AF7)", "UART4_RX (AF8)", "ETH_REF_CLK (AF11)", "ETH_RX_CLK (AF11)", "TIM2_CH2 (AF1)", "TIM5_CH2 (AF2)", "ADC123_IN1", "GPIO_Output", "GPIO_Input"] },
    { number: 25, name: "PA2", defaultFunction: "GPIO", alternateFunctions: ["USART2_TX (AF7)", "TIM2_CH3 (AF1)", "TIM5_CH3 (AF2)", "TIM9_CH1 (AF3)", "ETH_MDIO (AF11)", "ADC123_IN2", "GPIO_Output", "GPIO_Input"] },

    // ---- Pin 26–50 ----
    { number: 26, name: "PA3", defaultFunction: "GPIO", alternateFunctions: ["USART2_RX (AF7)", "TIM2_CH4 (AF1)", "TIM5_CH4 (AF2)", "TIM9_CH2 (AF3)", "USB_OTG_HS_ULPI_D0 (AF10)", "ETH_COL (AF11)", "ADC123_IN3", "GPIO_Output", "GPIO_Input"] },
    { number: 27, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 28, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 29, name: "PA4", defaultFunction: "GPIO", alternateFunctions: ["SPI1_NSS (AF5)", "SPI3_NSS (AF6)", "USART2_CK (AF7)", "USB_OTG_HS_SOF (AF12)", "DCMI_HSYNC (AF13)", "ADC12_IN4", "DAC_OUT1", "GPIO_Output", "GPIO_Input"] },
    { number: 30, name: "PA5", defaultFunction: "GPIO", alternateFunctions: ["SPI1_SCK (AF5)", "TIM2_CH1 (AF1)", "TIM8_CH1N (AF3)", "USB_OTG_HS_ULPI_CK (AF10)", "ADC12_IN5", "DAC_OUT2", "GPIO_Output", "GPIO_Input"] },
    { number: 31, name: "PA6", defaultFunction: "GPIO", alternateFunctions: ["SPI1_MISO (AF5)", "TIM1_BKIN (AF1)", "TIM3_CH1 (AF2)", "TIM8_BKIN (AF3)", "TIM13_CH1 (AF9)", "DCMI_PIXCLK (AF13)", "ADC12_IN6", "GPIO_Output", "GPIO_Input"] },
    { number: 32, name: "PA7", defaultFunction: "GPIO", alternateFunctions: ["SPI1_MOSI (AF5)", "TIM1_CH1N (AF1)", "TIM3_CH2 (AF2)", "TIM8_CH1N (AF3)", "TIM14_CH1 (AF9)", "ETH_CRS_DV (AF11)", "ETH_RX_DV (AF11)", "ADC12_IN7", "GPIO_Output", "GPIO_Input"] },
    { number: 33, name: "PC4", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN14", "ETH_RXD0 (AF11)", "GPIO_Output", "GPIO_Input"] },
    { number: 34, name: "PC5", defaultFunction: "GPIO", alternateFunctions: ["ADC12_IN15", "ETH_RXD1 (AF11)", "GPIO_Output", "GPIO_Input"] },
    { number: 35, name: "PB0", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH2N (AF1)", "TIM3_CH3 (AF2)", "TIM8_CH2N (AF3)", "USB_OTG_HS_ULPI_D1 (AF10)", "ETH_RXD2 (AF11)", "ADC12_IN8", "GPIO_Output", "GPIO_Input"] },
    { number: 36, name: "PB1", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH3N (AF1)", "TIM3_CH4 (AF2)", "TIM8_CH3N (AF3)", "USB_OTG_HS_ULPI_D2 (AF10)", "ETH_RXD3 (AF11)", "ADC12_IN9", "GPIO_Output", "GPIO_Input"] },
    { number: 37, name: "PB2", defaultFunction: "GPIO/BOOT1", alternateFunctions: ["GPIO_Output", "GPIO_Input"] },
    { number: 38, name: "PE7", defaultFunction: "GPIO", alternateFunctions: ["TIM1_ETR (AF1)", "FSMC_D4 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 39, name: "PE8", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH1N (AF1)", "FSMC_D5 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 40, name: "PE9", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH1 (AF1)", "FSMC_D6 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 41, name: "PE10", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH2N (AF1)", "FSMC_D7 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 42, name: "PE11", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH2 (AF1)", "SPI4_NSS (AF5)", "FSMC_D8 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 43, name: "PE12", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH3N (AF1)", "SPI4_SCK (AF5)", "FSMC_D9 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 44, name: "PE13", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH3 (AF1)", "SPI4_MISO (AF5)", "FSMC_D10 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 45, name: "PE14", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH4 (AF1)", "SPI4_MOSI (AF5)", "FSMC_D11 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 46, name: "PE15", defaultFunction: "GPIO", alternateFunctions: ["TIM1_BKIN (AF1)", "FSMC_D12 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 47, name: "PB10", defaultFunction: "GPIO", alternateFunctions: ["I2C2_SCL (AF4)", "SPI2_SCK (AF5)", "USART3_TX (AF7)", "USB_OTG_HS_ULPI_D3 (AF10)", "ETH_RX_ER (AF11)", "TIM2_CH3 (AF1)", "GPIO_Output", "GPIO_Input"] },
    { number: 48, name: "PB11", defaultFunction: "GPIO", alternateFunctions: ["I2C2_SDA (AF4)", "USART3_RX (AF7)", "USB_OTG_HS_ULPI_D4 (AF10)", "ETH_TX_EN (AF11)", "TIM2_CH4 (AF1)", "GPIO_Output", "GPIO_Input"] },
    { number: 49, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 50, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },

    // ---- Pin 51–75 ----
    { number: 51, name: "PB12", defaultFunction: "GPIO", alternateFunctions: ["SPI2_NSS (AF5)", "I2C2_SMBA (AF4)", "USART3_CK (AF7)", "TIM1_BKIN (AF1)", "CAN2_RX (AF9)", "USB_OTG_HS_ULPI_D5 (AF10)", "ETH_TXD0 (AF11)", "USB_OTG_HS_ID (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 52, name: "PB13", defaultFunction: "GPIO", alternateFunctions: ["SPI2_SCK (AF5)", "USART3_CTS (AF7)", "TIM1_CH1N (AF1)", "CAN2_TX (AF9)", "USB_OTG_HS_ULPI_D6 (AF10)", "ETH_TXD1 (AF11)", "GPIO_Output", "GPIO_Input"] },
    { number: 53, name: "PB14", defaultFunction: "GPIO", alternateFunctions: ["SPI2_MISO (AF5)", "USART3_RTS (AF7)", "TIM1_CH2N (AF1)", "TIM8_CH2N (AF3)", "TIM12_CH1 (AF9)", "USB_OTG_HS_DM (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 54, name: "PB15", defaultFunction: "GPIO", alternateFunctions: ["SPI2_MOSI (AF5)", "TIM1_CH3N (AF1)", "TIM8_CH3N (AF3)", "TIM12_CH2 (AF9)", "USB_OTG_HS_DP (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 55, name: "PD8", defaultFunction: "GPIO", alternateFunctions: ["USART3_TX (AF7)", "FSMC_D13 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 56, name: "PD9", defaultFunction: "GPIO", alternateFunctions: ["USART3_RX (AF7)", "FSMC_D14 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 57, name: "PD10", defaultFunction: "GPIO", alternateFunctions: ["USART3_CK (AF7)", "FSMC_D15 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 58, name: "PD11", defaultFunction: "GPIO", alternateFunctions: ["USART3_CTS (AF7)", "FSMC_A16 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 59, name: "PD12", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH1 (AF2)", "USART3_RTS (AF7)", "FSMC_A17 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 60, name: "PD13", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH2 (AF2)", "FSMC_A18 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 61, name: "PD14", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH3 (AF2)", "FSMC_D0 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 62, name: "PD15", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH4 (AF2)", "FSMC_D1 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 63, name: "PC6", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH1 (AF2)", "TIM8_CH1 (AF3)", "I2S2_MCK (AF5)", "USART6_TX (AF8)", "SDIO_D6 (AF12)", "DCMI_D0 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 64, name: "PC7", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH2 (AF2)", "TIM8_CH2 (AF3)", "I2S3_MCK (AF6)", "USART6_RX (AF8)", "SDIO_D7 (AF12)", "DCMI_D1 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 65, name: "PC8", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH3 (AF2)", "TIM8_CH3 (AF3)", "USART6_CK (AF8)", "SDIO_D0 (AF12)", "DCMI_D2 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 66, name: "PC9", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH4 (AF2)", "TIM8_CH4 (AF3)", "I2C3_SDA (AF4)", "I2S_CKIN (AF5)", "SDIO_D1 (AF12)", "DCMI_D3 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 67, name: "PA8", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH1 (AF1)", "I2C3_SCL (AF4)", "USART1_CK (AF7)", "USB_OTG_FS_SOF (AF10)", "MCO1", "GPIO_Output", "GPIO_Input"] },
    { number: 68, name: "PA9", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH2 (AF1)", "I2C3_SMBA (AF4)", "USART1_TX (AF7)", "USB_OTG_FS_VBUS (AF10)", "DCMI_D0 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 69, name: "PA10", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH3 (AF1)", "USART1_RX (AF7)", "USB_OTG_FS_ID (AF10)", "DCMI_D1 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 70, name: "PA11", defaultFunction: "GPIO", alternateFunctions: ["TIM1_CH4 (AF1)", "USART1_CTS (AF7)", "CAN1_RX (AF9)", "USB_OTG_FS_DM (AF10)", "GPIO_Output", "GPIO_Input"] },
    { number: 71, name: "PA12", defaultFunction: "GPIO", alternateFunctions: ["TIM1_ETR (AF1)", "USART1_RTS (AF7)", "CAN1_TX (AF9)", "USB_OTG_FS_DP (AF10)", "GPIO_Output", "GPIO_Input"] },
    { number: 72, name: "PA13", defaultFunction: "SWDIO", alternateFunctions: ["JTMS (AF0)", "SWDIO (AF0)", "GPIO_Output", "GPIO_Input"] },
    { number: 73, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 74, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 75, name: "PA14", defaultFunction: "SWCLK", alternateFunctions: ["JTCK (AF0)", "SWCLK (AF0)", "GPIO_Output", "GPIO_Input"] },

    // ---- Pin 76–100 ----
    { number: 76, name: "PA15", defaultFunction: "JTDI", alternateFunctions: ["JTDI (AF0)", "TIM2_CH1 (AF1)", "TIM2_ETR (AF1)", "SPI1_NSS (AF5)", "SPI3_NSS (AF6)", "GPIO_Output", "GPIO_Input"] },
    { number: 77, name: "PC10", defaultFunction: "GPIO", alternateFunctions: ["SPI3_SCK (AF6)", "USART3_TX (AF7)", "UART4_TX (AF8)", "SDIO_D2 (AF12)", "DCMI_D8 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 78, name: "PC11", defaultFunction: "GPIO", alternateFunctions: ["SPI3_MISO (AF6)", "USART3_RX (AF7)", "UART4_RX (AF8)", "SDIO_D3 (AF12)", "DCMI_D4 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 79, name: "PC12", defaultFunction: "GPIO", alternateFunctions: ["SPI3_MOSI (AF6)", "USART3_CK (AF7)", "UART5_TX (AF8)", "SDIO_CK (AF12)", "DCMI_D9 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 80, name: "PD0", defaultFunction: "GPIO", alternateFunctions: ["CAN1_RX (AF9)", "FSMC_D2 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 81, name: "PD1", defaultFunction: "GPIO", alternateFunctions: ["CAN1_TX (AF9)", "FSMC_D3 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 82, name: "PD2", defaultFunction: "GPIO", alternateFunctions: ["TIM3_ETR (AF2)", "UART5_RX (AF8)", "SDIO_CMD (AF12)", "DCMI_D11 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 83, name: "PD3", defaultFunction: "GPIO", alternateFunctions: ["USART2_CTS (AF7)", "FSMC_CLK (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 84, name: "PD4", defaultFunction: "GPIO", alternateFunctions: ["USART2_RTS (AF7)", "FSMC_NOE (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 85, name: "PD5", defaultFunction: "GPIO", alternateFunctions: ["USART2_TX (AF7)", "FSMC_NWE (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 86, name: "PD6", defaultFunction: "GPIO", alternateFunctions: ["USART2_RX (AF7)", "FSMC_NWAIT (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 87, name: "PD7", defaultFunction: "GPIO", alternateFunctions: ["USART2_CK (AF7)", "FSMC_NE1 (AF12)", "GPIO_Output", "GPIO_Input"] },
    { number: 88, name: "PB3", defaultFunction: "JTDO", alternateFunctions: ["JTDO (AF0)", "TRACESWO (AF0)", "TIM2_CH2 (AF1)", "SPI1_SCK (AF5)", "SPI3_SCK (AF6)", "GPIO_Output", "GPIO_Input"] },
    { number: 89, name: "PB4", defaultFunction: "JNTRST", alternateFunctions: ["JNTRST (AF0)", "TIM3_CH1 (AF2)", "SPI1_MISO (AF5)", "SPI3_MISO (AF6)", "GPIO_Output", "GPIO_Input"] },
    { number: 90, name: "PB5", defaultFunction: "GPIO", alternateFunctions: ["TIM3_CH2 (AF2)", "I2C1_SMBA (AF4)", "SPI1_MOSI (AF5)", "SPI3_MOSI (AF6)", "CAN2_RX (AF9)", "USB_OTG_HS_ULPI_D7 (AF10)", "ETH_PPS_OUT (AF11)", "DCMI_D10 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 91, name: "PB6", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH1 (AF2)", "I2C1_SCL (AF4)", "USART1_TX (AF7)", "CAN2_TX (AF9)", "DCMI_D5 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 92, name: "PB7", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH2 (AF2)", "I2C1_SDA (AF4)", "USART1_RX (AF7)", "FSMC_NL (AF12)", "DCMI_VSYNC (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 93, name: "BOOT0", defaultFunction: "Boot", alternateFunctions: [] },
    { number: 94, name: "PB8", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH3 (AF2)", "TIM10_CH1 (AF3)", "I2C1_SCL (AF4)", "CAN1_RX (AF9)", "ETH_TXD3 (AF11)", "SDIO_D4 (AF12)", "DCMI_D6 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 95, name: "PB9", defaultFunction: "GPIO", alternateFunctions: ["TIM4_CH4 (AF2)", "TIM11_CH1 (AF3)", "I2C1_SDA (AF4)", "SPI2_NSS (AF5)", "CAN1_TX (AF9)", "SDIO_D5 (AF12)", "DCMI_D7 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 96, name: "PE0", defaultFunction: "GPIO", alternateFunctions: ["TIM4_ETR (AF2)", "FSMC_NBL0 (AF12)", "DCMI_D2 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 97, name: "PE1", defaultFunction: "GPIO", alternateFunctions: ["FSMC_NBL1 (AF12)", "DCMI_D3 (AF13)", "GPIO_Output", "GPIO_Input"] },
    { number: 98, name: "VSS", defaultFunction: "Power", alternateFunctions: [] },
    { number: 99, name: "VDD", defaultFunction: "Power", alternateFunctions: [] },
    { number: 100, name: "PDR_ON", defaultFunction: "Power", alternateFunctions: [] },
  ],
};
